# Copyright (c) 2017-2020 Kent R. Spillner <kspillner@acm.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

FROM ${REPOSITORY}/aur-pkgbuild-base-multilib:${ARCH_VERSION}

ENV ARCH_VERSION ${ARCH_VERSION}

ENV VERSION ${VERSION}

ENV REFRESHED_AT ${DATE}

# Ensure man(1) is installed
RUN [ "/usr/bin/pacman", "--noconfirm", "--sync", "--quiet", "man" ]

# Populate Xen pkg spec
COPY --chown=_build:_build aur-xen/ /opt/aur-xen/

USER _build
WORKDIR /opt/aur-xen

# Install initial set of build deps in order to save bandwidth when frequently testing patches
RUN [ "/usr/bin/makepkg", "--needed", "--nobuild", "--noconfirm", "--noextract", "--skippgpcheck", "--skipchecksums", "--syncdeps" ]

ADD --chown=_build:_build aur-xen_PKGBUILD.patch /opt/aur-xen/
ADD --chown=_build:_build gcc-10-fixes.patch /opt/aur-xen/
ADD --chown=_build:_build gcc-10-ipxe-fixes.patch /opt/aur-xen/

RUN [ "/usr/sbin/patch", "-p2", "PKGBUILD", "aur-xen_PKGBUILD.patch" ]

# Re-sync deps after patching
RUN [ "/usr/bin/makepkg", "--needed", "--nobuild", "--noconfirm", "--skippgpcheck", "--skipchecksums", "--syncdeps" ]

# Print checksums for distfiles
RUN [ "/usr/bin/makepkg", "--geninteg" ]

# Build the package
# TODO: figure out how to import Xen's signing key into _build's keychain
CMD [ "/usr/bin/makepkg", "--clean", "--needed", "--noconfirm", "--rmdeps", "--skippgpcheck", "--syncdeps" ]
