# Copyright (c) 2017-2018 Kent R. Spillner <kspillner@acm.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

FROM ${REPOSITORY}/aur-pkgbuild-base-multilib:${ARCH_VERSION}

ENV ARCH_VERSION ${ARCH_VERSION}

ENV VERSION ${VERSION}

ENV REFRESHED_AT ${DATE}

# Ensure man(1) is installed
RUN [ "/usr/bin/pacman", "--noconfirm", "--sync", "--quiet", "man" ]

# Populate Xen pkg spec
COPY --chown=_build:_build aur-xen/ /opt/aur-xen/

# Copy PKGBUILD.patch
COPY --chown=_build:_build PKGBUILD.patch /opt/aur-xen/

# Copy tools_libacpi_Makefile.patch
COPY --chown=_build:_build tools_libacpi_Makefile.patch /opt/aur-xen/

USER _build
WORKDIR /opt/aur-xen

# Patch PKGBUILD to apply tools_libacpi_Makefile.patch
RUN [ "/bin/sh", "-c", "/usr/bin/patch -p0 <PKGBUILD.patch" ]

# Build the package
# TODO: figure out how to import Xen's signing key into _build's keychain
CMD [ "/usr/bin/makepkg", "--clean", "--needed", "--noconfirm", "--rmdeps", "--skippgpcheck", "--syncdeps" ]
